### ISSUE TITLE
Hash

### ISSUE THREAD

**Issue by scs-ben** [ratosh/pirarucu#130]
This is for TCEC
setoption name Hash value 16384
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at pirarucu.hash.TranspositionTable.resize(TranspositionTable.kt:47)
        at pirarucu.uci.InputHandler.setOption(InputHandler.kt:47)
        at pirarucu.uci.UciInput.process(UciInput.kt:24)
        at pirarucu.MainKt.main(Main.kt:56)

**Comment by ratosh** [comment]
It is a limitation from the JVM, can you start it with the argument -Xms16384m?

**Comment by scs-ben** [comment]
-Xms16400m works
