### ISSUE TITLE
macOS: UCI command go movetime x

### ISSUE THREAD

**Issue by twoplan** [ratosh/pirarucu#176]
I ran some test positions with our engine. Your engine seems not to support uci command **go movetime x** or **go depth y**. In both cases Pirarucu answers instantly.
```
Starting engine /Users/max/chess/Pirarucu/pirarucu-3.07 ...
>> uci
<< Initialized in 404 ms
<< Handling setoption threads 1
<< id name Pirarucu v3.0.7
<< id author Raoni Campos
<< option name Hash type spin default 256 min 1 max 8192
<< option name PawnHash type spin default 32 min 1 max 1024
<< option name Threads type spin default 1 min 1 max 128
<< uciok
>> setoption name Hash value 128
>> setoption name Contempt value 0
>> setoption name Threads value 1
>> setoption name Cores value 1
>> setoption name Max CPUs value 1

Pos 1
1kr5/3n4/q3p2p/p2n2p1/PppB1P2/5BP1/1P2Q2P/3R2K1 w - - bm f5; id "STS(v1.0) Undermine.001"; c0 "f5=10, Be5+=2, Bf2=3, Bg4=2"; c7 "f5 Be5+ Bf2 Bg4"; c8 "10 2 3 2"; c9 "f4f5 d4e5 d4f2 f3g4";

2019-06-28T09:31:41.547018 >> isready
2019-06-28T09:31:41.547095 << Handling setoption Hash 128
2019-06-28T09:31:41.617396 << Handling setoption Contempt 0
2019-06-28T09:31:41.617483 << Setting Contempt with value 0
2019-06-28T09:31:41.619289 << java.lang.NoSuchFieldException: Contempt
2019-06-28T09:31:41.619420 << at java.lang.Class.getDeclaredField(Class.java:2070)
2019-06-28T09:31:41.619521 << at pirarucu.util.PlatformSpecific.applyConfig(PlatformSpecific.kt:82)
2019-06-28T09:31:41.619605 << at pirarucu.uci.InputHandler.setOption(InputHandler.kt:60)
2019-06-28T09:31:41.619674 << at pirarucu.uci.UciInput.process(UciInput.kt:25)
2019-06-28T09:31:41.619727 << at pirarucu.MainKt.main(Main.kt:66)
2019-06-28T09:31:41.619769 << Handling setoption Threads 1
2019-06-28T09:31:41.620035 << Handling setoption Cores 1
2019-06-28T09:31:41.620124 << Setting Cores with value 1
2019-06-28T09:31:41.620222 << java.lang.NoSuchFieldException: Cores
2019-06-28T09:31:41.620346 << at java.lang.Class.getDeclaredField(Class.java:2070)
2019-06-28T09:31:41.620485 << at pirarucu.util.PlatformSpecific.applyConfig(PlatformSpecific.kt:82)
2019-06-28T09:31:41.620602 << at pirarucu.uci.InputHandler.setOption(InputHandler.kt:60)
2019-06-28T09:31:41.620700 << at pirarucu.uci.UciInput.process(UciInput.kt:25)
2019-06-28T09:31:41.620777 << at pirarucu.MainKt.main(Main.kt:66)
2019-06-28T09:31:41.620860 << Handling setoption Max value
2019-06-28T09:31:41.620965 << java.lang.NumberFormatException: For input string: "value"
2019-06-28T09:31:41.621120 << at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
2019-06-28T09:31:41.621199 << at java.lang.Integer.parseInt(Integer.java:580)
2019-06-28T09:31:41.621269 << at java.lang.Integer.parseInt(Integer.java:615)
2019-06-28T09:31:41.621352 << at pirarucu.uci.InputHandler.setOption(InputHandler.kt:60)
2019-06-28T09:31:41.621422 << at pirarucu.uci.UciInput.process(UciInput.kt:25)
2019-06-28T09:31:41.621475 << at pirarucu.MainKt.main(Main.kt:66)
2019-06-28T09:31:41.621491 << readyok
2019-06-28T09:31:41.621504 >> ucinewgame
2019-06-28T09:31:41.621510 >> position fen 1kr5/3n4/q3p2p/p2n2p1/PppB1P2/5BP1/1P2Q2P/3R2K1 w - - 0 1
2019-06-28T09:31:41.621537 >> go movetime 196
2019-06-28T09:31:41.653613 << info depth 1 time 8 score cp 20 nps 8625 nodes 69 pv f4g5
2019-06-28T09:31:41.653685 << info hashfull 0
2019-06-28T09:31:41.653709 << bestmove f4g5
Engine best move is not one of the solution moves??

Total points for this theme so far : 0/10
```
```
2019-06-28T09:53:03.397473 >> position fen 1kr5/3n4/q3p2p/p2n2p1/PppB1P2/5BP1/1P2Q2P/3R2K1 w - - 0 1
2019-06-28T09:53:03.397492 >> go depth 5
2019-06-28T09:53:03.429418 << info depth 1 time 8 score cp 20 nps 8625 nodes 69 pv f4g5
2019-06-28T09:53:03.429496 << info hashfull 0
2019-06-28T09:53:03.429519 << bestmove f4g5
Engine best move is not one of the solution moves??

Total points for this theme so far : 0/10
```

Is this a macOS issue, or didn't you implement go movetime/depth?

**Comment by ratosh** [comment]
Hello,

Currently it does not support movetime option, I'll add support to it on next release. It should support depth, I need to check what went wrong with depth option.

Thanks for testing the engine,
Raoni Campos.

**Comment by ratosh** [comment]
Fixed for the next release.
